[tool.poetry]
name = "noble_rag"
version = "0.1.0"
description = "Knowledge base for Noble"
authors = ["tran-kim-quang <trankimquang1603@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
lightrag-hku = {extras = ["api"], version = "^1.4.10"}
pydantic-settings = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
