[tool.poetry]
name = "noble_rag"
version = "0.1.0"
description = "Knowledge base for Noble"
authors = ["tran-kim-quang <trankimquang1603@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
haystack-ai = "^2.0.0"
pydantic-settings = "^2.0.0"
requests = "^2.32.5"
numpy = "^2.3.3"
sounddevice = "^0.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
